library("memisc")
library("lmtest")
library("ggplot2")
library("dplyr")
library("foreign")
library("vcd")
library("devtools")
library("hexbin")
library("pander")
library("sjPlot")
library("knitr")
library("psych")
library("sgof")
library("car")
library("rlms")
#devtools::install_github("bdemeshev/rlms")

h <- read.rlms("r21i_os24a.sav")
saveRDS(h, file = "r21i_os24a.rds")
